# Generated by Django 5.2 on 2025-04-14 12:48

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='content',
            new_name='question',
        ),
        migrations.RemoveField(
            model_name='keyword',
            name='text',
        ),
        migrations.RemoveField(
            model_name='question',
            name='keyword',
        ),
        migrations.AddField(
            model_name='keyword',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='建立時間'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='keyword',
            name='keyword',
            field=models.CharField(default=datetime.datetime(2025, 4, 14, 12, 46, 51, 727957, tzinfo=datetime.timezone.utc), max_length=100, unique=True, verbose_name='關鍵字'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='keyword',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新時間'),
        ),
        migrations.AddField(
            model_name='question',
            name='answer',
            field=models.TextField(default=datetime.datetime(2025, 4, 14, 0, 0), verbose_name='答案內容'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='keywords',
            field=models.ManyToManyField(related_name='questions', to='myapp.keyword'),
        ),
        migrations.AddField(
            model_name='question',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新時間'),
        ),
    ]
