# Generated by Django 5.2 on 2025-04-14 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_content_question_question_remove_keyword_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='keywordgroup',
            name='description',
            field=models.TextField(blank=True, verbose_name='主題描述'),
        ),
    ]
