# Generated by Django 5.2 on 2025-07-14 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_keywordgroup_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='GitBookPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('url', models.URLField(blank=True, null=True)),
                ('content', models.TextField()),
            ],
        ),
    ]
