# Generated by Django 5.2.4 on 2025-08-11 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_gitbookpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='gitbookpage',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pages', to='myapp.keywordgroup', verbose_name='四大主題'),
        ),
        migrations.AddField(
            model_name='gitbookpage',
            name='group_key',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='一級目錄鍵'),
        ),
        migrations.AddField(
            model_name='gitbookpage',
            name='keywords',
            field=models.ManyToManyField(blank=True, related_name='pages', to='myapp.keyword', verbose_name='關聯關鍵字'),
        ),
    ]
