# Generated by Django 5.2.4 on 2025-08-11 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_gitbookpage_group_gitbookpage_group_key_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gitbookpage',
            name='group',
        ),
        migrations.RemoveField(
            model_name='gitbookpage',
            name='group_key',
        ),
        migrations.RemoveField(
            model_name='gitbookpage',
            name='keywords',
        ),
    ]
