# Generated by Django 5.2.4 on 2025-09-22 21:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_remove_gitbookpage_group_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gitbookpage',
            name='url',
        ),
        migrations.AddField(
            model_name='gitbookpage',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gitbook_pages', to='myapp.keywordgroup', verbose_name='文章群組'),
        ),
    ]
