# Generated by Django 5.2.4 on 2025-09-22 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_remove_gitbookpage_url_gitbookpage_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='gitbookpage',
            name='keywords',
            field=models.ManyToManyField(blank=True, related_name='gitbook_pages', to='myapp.keyword', verbose_name='相關關鍵字'),
        ),
    ]
